apiVersion: v1
kind: Namespace
metadata:
  name: fleet-manager
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: fleet-manager
spec:
  replicas: 1
  serviceName: mongodb
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:8.0.3
          resources:
            requests:
              cpu: "0.3"
              memory: "0.5Gi"
            limits:
              cpu: "4"
              memory: "2Gi"
          volumeMounts:
            - mountPath: "/data/db"
              name: mongodb
              readOnly: false
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "mongo-root-user"
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: github-settings
                  key: SHARED_DB_PASSWORD
                  optional: false
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongodb
            readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  namespace: fleet-manager
  labels:
    app: mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: fleet-manager
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      name: mongodb
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express
  namespace: fleet-manager
  labels:
    app: mongodb-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-express
  template:
    metadata:
      labels:
        app: mongodb-express
    spec:
      containers:
        - name: mongodb-express
          image: mongo-express:1.0.2
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "0.2"
              memory: "0.2Gi"
            limits:
              cpu: "0.2"
              memory: "0.2Gi"
          env:
            - name: ME_CONFIG_BASICAUTH
              value: "false"
            - name: ME_CONFIG_HEALTH_CHECK_PATH
              value: "/status"
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb.fleet-manager.svc.cluster.local
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "mongo-root-user"
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: ""
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: github-settings
                  key: SHARED_DB_PASSWORD
                  optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-express
  namespace: fleet-manager
spec:
  selector:
    app: mongodb-express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
