apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crd-resources
  namespace: flux-system
spec:
  interval: 10s
  prune: true
  wait: true
  dependsOn:
    - name: base
      namespace: flux-system
  path: "./kubernetes/crd-resources"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
